from flask import Flask, render_template, request, redirect, session
from werkzeug.security import generate_password_hash, check_password_hash
from dotenv import load_dotenv
from flask import make_response
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
import os
import psycopg2
import psycopg2.errors

load_dotenv()

app = Flask(__name__)
app.secret_key = "smart_expense_secret_key"

conn = psycopg2.connect(os.getenv("DATABASE_URL"))
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    amount FLOAT,
    type TEXT,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id)
)
""")
conn.commit()


@app.route("/")
def home():
    if "user_id" not in session:
        return redirect("/login")

    filter_type = request.args.get("type", "all")
    search = request.args.get("search", "")

    query = "SELECT * FROM transactions WHERE user_id = %s"
    params = [session["user_id"]]

    if filter_type == "income":
        query += " AND type = %s"
        params.append("income")
    elif filter_type == "expense":
        query += " AND type = %s"
        params.append("expense")

    if search:
        query += " AND title ILIKE %s"
        params.append(f"%{search}%")

    query += " ORDER BY id DESC"

    cursor.execute(query, tuple(params))
    transactions = cursor.fetchall()

    cursor.execute(
        "SELECT * FROM transactions WHERE user_id = %s",
        (session["user_id"],)
    )
    all_transactions = cursor.fetchall()

    total_income = sum(t[2] for t in all_transactions if t[3] == "income")
    total_expense = sum(t[2] for t in all_transactions if t[3] == "expense")
    balance = total_income - total_expense

    return render_template(
        "index.html",
        transactions=transactions,
        total_income=total_income,
        total_expense=total_expense,
        balance=balance,
        filter_type=filter_type,
        search=search
    )


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"].strip().lower()
        raw_password = request.form["password"]

        hashed_password = generate_password_hash(raw_password, method="pbkdf2:sha256")

        try:
            cursor.execute(
                "INSERT INTO users (name, email, password) VALUES (%s, %s, %s)",
                (name, email, hashed_password)
            )
            conn.commit()
            return redirect("/login")

        except psycopg2.errors.UniqueViolation:
            conn.rollback()
            return "Email already registered. Please login."

    return render_template("register.html")


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form["email"].strip().lower()
        password = request.form["password"]

        cursor.execute("SELECT id, name, email, password FROM users WHERE email = %s", (email,))
        user = cursor.fetchone()

        print("USER:", user)  # debug

        if user:
            print("Stored hash:", user[3])
            print("Entered password:", password)

            if check_password_hash(user[3], password):
                session["user_id"] = user[0]
                session["user_name"] = user[1]
                return redirect("/")

        return "Invalid email or password"

    return render_template("login.html")


@app.route("/logout")
def logout():
    session.clear()
    return redirect("/login")


@app.route("/add", methods=["POST"])
def add():
    if "user_id" not in session:
        return redirect("/login")

    title = request.form["title"]
    amount = request.form["amount"]
    t_type = request.form["type"]

    cursor.execute(
        "INSERT INTO transactions (title, amount, type, user_id) VALUES (%s, %s, %s, %s)",
        (title, amount, t_type, session["user_id"])
    )
    conn.commit()

    return redirect("/")


@app.route("/delete/<int:id>")
def delete(id):
    if "user_id" not in session:
        return redirect("/login")

    cursor.execute(
        "DELETE FROM transactions WHERE id = %s AND user_id = %s",
        (id, session["user_id"])
    )
    conn.commit()

    return redirect("/")


@app.route("/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    if "user_id" not in session:
        return redirect("/login")

    if request.method == "POST":
        title = request.form["title"]
        amount = request.form["amount"]
        t_type = request.form["type"]

        cursor.execute(
            "UPDATE transactions SET title=%s, amount=%s, type=%s WHERE id=%s AND user_id=%s",
            (title, amount, t_type, id, session["user_id"])
        )
        conn.commit()

        return redirect("/")

    cursor.execute(
        "SELECT * FROM transactions WHERE id = %s AND user_id = %s",
        (id, session["user_id"])
    )
    transaction = cursor.fetchone()

    return render_template("edit.html", transaction=transaction)

@app.route("/monthly-report")
def monthly_report():
    if "user_id" not in session:
        return redirect("/login")

    month = request.args.get("month")

    if month:
        cursor.execute("""
            SELECT * FROM transactions
            WHERE user_id = %s
            AND TO_CHAR(date, 'YYYY-MM') = %s
            ORDER BY date DESC
        """, (session["user_id"], month))
    else:
        cursor.execute("""
            SELECT * FROM transactions
            WHERE user_id = %s
            ORDER BY date DESC
        """, (session["user_id"],))

    data = cursor.fetchall()

    income = sum(t[2] for t in data if t[3] == "income")
    expense = sum(t[2] for t in data if t[3] == "expense")
    balance = income - expense

    return render_template(
        "monthly_report.html",
        transactions=data,
        income=income,
        expense=expense,
        balance=balance,
        month=month
    )

@app.route("/export-pdf")
def export_pdf():
    if "user_id" not in session:
        return redirect("/login")

    month = request.args.get("month", "")

    if month:
        cursor.execute("""
            SELECT * FROM transactions
            WHERE user_id = %s
            AND TO_CHAR(date, 'YYYY-MM') = %s
            ORDER BY date DESC
        """, (session["user_id"], month))
    else:
        cursor.execute("""
            SELECT * FROM transactions
            WHERE user_id = %s
            ORDER BY date DESC
        """, (session["user_id"],))

    data = cursor.fetchall()

    income = sum(t[2] for t in data if t[3] == "income")
    expense = sum(t[2] for t in data if t[3] == "expense")
    balance = income - expense

    response = make_response()
    response.headers["Content-Type"] = "application/pdf"
    response.headers["Content-Disposition"] = "attachment; filename=monthly_report.pdf"

    pdf = canvas.Canvas(response.stream, pagesize=A4)
    width, height = A4

    y = height - 50

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Smart Expense Tracker - Monthly Report")

    y -= 30
    pdf.setFont("Helvetica", 11)
    pdf.drawString(50, y, f"Month: {month if month else 'All'}")

    y -= 30
    pdf.drawString(50, y, f"Total Income: Rs. {income}")
    y -= 20
    pdf.drawString(50, y, f"Total Expense: Rs. {expense}")
    y -= 20
    pdf.drawString(50, y, f"Balance: Rs. {balance}")

    y -= 40
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(50, y, "Title")
    pdf.drawString(200, y, "Amount")
    pdf.drawString(300, y, "Type")
    pdf.drawString(400, y, "Date")

    pdf.setFont("Helvetica", 10)

    for t in data:
        y -= 20

        if y < 50:
            pdf.showPage()
            y = height - 50

        pdf.drawString(50, y, str(t[1]))
        pdf.drawString(200, y, f"Rs. {t[2]}")
        pdf.drawString(300, y, str(t[3]))
        pdf.drawString(400, y, t[4].strftime("%d-%m-%Y"))

    pdf.save()
    return response

if __name__ == "__main__":
    app.run(debug=True)